name: collection-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "react-app"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: npm install
        run: |
          npm install
      - run: echo REACT_APP_REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY >> .env
      - run: cat .env
      - name: Build App
        run: npm run build
      - name: App Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build